spring:
  application:
    name: rcart-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abdulrasheedshaikgit/RCart-Config-Repo.git
          default-label: dev
server:
  port: 8080